[package]
name = "ex"
version = "0.1.0"
authors = ["dshade"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
wasm-bindgen = "0.2.56"

[lib]
crate-type=["cdylib"]
